spring:
  application:
    name: cloud-zipkin

server:
  port: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false

#2（共2个步骤）在这些项目的 application.yml 配置文件中增加 Zipkin Server 的地址即可
#spring:
#  zipkin:
#    base-url: http://localhost:9411