spring:
  application:
    name: cloud-ribbon
  #服务链路追踪配置
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8764

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/